language: node_js
node_js:
  - "10.14.1"
before_script:
  - npm install
   -g gulp-cli
script:
 - gulp build
 - npm test

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variabl
#  keep_history: true
#  on:
#    branch: develop
after_success:
  - npm run coverage